### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by daniel-sosna** [daniel-sosna/Excel-formatter-for-B1#7]
- [x] Add option to set beginning of the index
- [ ] update VAT (Finland: 24 => 25.5)
- [x] Add quotes validation in the filenames input
